In [3]:
import numpy as np
import torch

In [4]:
li = np.array([[1, 2], [3, 4]])
#넘파이배열을 텐서로 변환
tensor1 = torch.tensor(li)
tensor2 = torch.as_tensor(li)
tensor3 = torch.from_numpy(li)
print(tensor1)
print(tensor2)
print(tensor3)

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)


In [5]:
#텐서를 넘파이배열로 변환
print(tensor1.numpy())
print(tensor2.numpy())
print(tensor3.numpy())

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [6]:
torch.manual_seed(0) #랜덤시드 고정
a = torch.rand(5) # 0 ~ 1 사이의 5개의 난수
b = torch.randn(5) # 평균 0, 표준편차 1인 5개의 난수
c = torch.randint(10, size=(5,)) # 0~9 사이의 5개의 난수
print(a)
print(b)
print(c)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([ 0.5507,  0.2704,  0.6472,  0.2490, -0.3354])
tensor([8, 4, 3, 6, 9])


In [7]:
print(torch.arange(1, 10)) # 1~9
print(torch.ones((2, 5))) # 2행 5열, 1로 채움
print(torch.zeros((3, 5))) #3행 5열, 0으로 채움
print(torch.linspace(0, 10, 5)) # 0~10, 5등분

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])


In [8]:
#텐서의 형상 변환(reshape)
t1 = torch.ones(4, 3)
t2 = t1.view(3, 4) #3행 4열로 변환
t3 = t1.view(12) #1차원 배열로 변환
print(t1)
print(t2)
print(t3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])


In [9]:
t1.view(1, 3, 4) #3차원으로 변환

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

> iris 데이터셋

In [13]:
from sklearn.datasets import load_iris
# iris 데이터셋 로딩
X, y = load_iris(return_X_y=True)

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(
X, y, random_state=10, test_size=0.2, stratify=y, shuffle=True)
print(len(X_train))

120


In [15]:
#신경망 모형 정의
from torch import nn
import torch.nn.functional as F

class Model(nn.Module):
    def __init__(self, input_dim):
        super(Model, self).__init__()
        #input layer, Linear 선형함수(1차함수)
        self.layer1 = nn.Linear(input_dim,50) #input nodes, output nodes 50
        self.layer2 = nn.Linear(50, 20)
        self.layer3 = nn.Linear(20, 3)
    def forward(self, x):
        x = F.relu(self.layer1(x))
        x = F.relu(self.layer2(x))
        # 출력층의 활성화함수 - 소프트맥스
        x = F.softmax(self.layer3(x), dim=0)
        return x

In [16]:
import torch

# 초기화함수의 input_dim으로 변수개수가 전달됨
model = Model(X_train.shape[1])
#최적화함수 정의
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
#손실함수 정의
loss_fn = nn.CrossEntropyLoss()
epochs = 100

In [17]:
from torch.autograd import Variable

#넘파이배열로부터 텐서를 만들고
X_train = Variable(torch.from_numpy(X_train)).float()
y_train = Variable(torch.from_numpy(y_train)).long()

for epoch in range(1, epochs+1):
    print("Epoch",epoch)

    #예측값
    y_pred = model(X_train)
    #손실함수에 예측값과 실제값을 입력
    loss = loss_fn(y_pred, y_train)
    print('loss:',loss.item())

    # 경사 초기화
    optimizer.zero_grad()   # 가중치, 편향
    loss.backward() # 역전파
    optimizer.step() # 가중치 업데이트

Epoch 1
loss: 1.0980700254440308
Epoch 2
loss: 1.097053050994873
Epoch 3
loss: 1.096076488494873
Epoch 4
loss: 1.0948431491851807
Epoch 5
loss: 1.0936310291290283
Epoch 6
loss: 1.092368245124817
Epoch 7
loss: 1.0912740230560303
Epoch 8
loss: 1.0903372764587402
Epoch 9
loss: 1.0895863771438599
Epoch 10
loss: 1.0889297723770142
Epoch 11
loss: 1.0883090496063232
Epoch 12
loss: 1.0878071784973145
Epoch 13
loss: 1.087348461151123
Epoch 14
loss: 1.086920142173767
Epoch 15
loss: 1.0865323543548584
Epoch 16
loss: 1.086174488067627
Epoch 17
loss: 1.0858628749847412
Epoch 18
loss: 1.0855845212936401
Epoch 19
loss: 1.0854016542434692
Epoch 20
loss: 1.085187315940857
Epoch 21
loss: 1.0849668979644775
Epoch 22
loss: 1.0847266912460327
Epoch 23
loss: 1.0845065116882324
Epoch 24
loss: 1.0842607021331787
Epoch 25
loss: 1.0840308666229248
Epoch 26
loss: 1.0838323831558228
Epoch 27
loss: 1.0836454629898071
Epoch 28
loss: 1.0834791660308838
Epoch 29
loss: 1.0833290815353394
Epoch 30
loss: 1.0831936597824

In [ ]:
# Prediction
X_test = Variable(torch.from_numpy(X_test)).float()
pred = model(X_test)

# 모형의 정확도 측정
from sklearn.metrics import accuracy_score
accuracy_score(y_test, np.argmax(pred.data.numpy(), axis=1))
                        # 최대값의 인덱스값

In [24]:
# 모델 저장
torch.save(model, "c:/vscode/data/iris/iris-torch.model")

In [25]:
# 모델 불러오기
model2 = torch.load("c:/vscode/data/iris/iris-torch.model")

In [27]:
from torchinfo import summary
summary(model, input_size=(32, 4))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [32, 3]                   --
├─Linear: 1-1                            [32, 50]                  250
├─Linear: 1-2                            [32, 20]                  1,020
├─Linear: 1-3                            [32, 3]                   63
Total params: 1,333
Trainable params: 1,333
Non-trainable params: 0
Total mult-adds (M): 0.04
Input size (MB): 0.00
Forward/backward pass size (MB): 0.02
Params size (MB): 0.01
Estimated Total Size (MB): 0.02

> gpu 사용법

In [1]:
import torch
#gpu 사용 가능 여부
print(torch.cuda.is_available())

True


In [2]:
#gpu 장치의 인덱스
print(torch.cuda.current_device())

0


In [3]:
# 사용가능한 gpu 장치수
print(torch.cuda.device_count())

1


In [4]:
# gpu의 이름
print(torch.cuda.get_device_name(0))

NVIDIA GeForce GTX 1050 Ti


In [ ]:
import torch
# Default CUDA device
cuda = torch.device('cuda')
# 텐서 자료를 gpu에 저장
a = torch.tensor([1, 2], device=cuda)
b = torch.tensor([1, 2]).cuda()
c = torch.tensor([1, 2]).to(device=cuda)
print(a)
print(b)
print(c)

In [ ]:
#사용하지 않는 텐서 정리
torch.cuda.empty_cache()